# Generated by Django 5.1.2 on 2025-09-20 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trancherecord',
            name='deduction_tax_rate',
            field=models.DecimalField(decimal_places=5, default=10.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trancherecord',
            name='option1_tax_rate',
            field=models.DecimalField(decimal_places=5, default=10.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trancherecord',
            name='option2_tax_rate',
            field=models.DecimalField(decimal_places=5, default=10.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trancherecord',
            name='vat_rate',
            field=models.DecimalField(decimal_places=5, default=12.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trancherecord',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=5, default=10.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='ReceivableVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('total_expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('processed', 'Processed')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('selected_tranches', models.ManyToManyField(related_name='receivable_vouchers', to='sparc.tranchepayment')),
                ('tranche_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_vouchers', to='sparc.trancherecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
