# Generated by Django 5.1.2 on 2025-09-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0002_alter_trancherecord_deduction_tax_rate_and_more'),
    ]

    operations = [
    ]
