# Generated by Django 5.1.2 on 2025-09-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0003_auto_20250920_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivableVoucher',
        ),
    ]
