# Generated by Django 5.1.2 on 2025-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0004_delete_receivablevoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranchepayment',
            name='combined_voucher_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
