# Generated by Django 5.1.2 on 2025-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0006_commissiondetail_percentage_of_particulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiondetail3',
            name='percentage_of_particulars',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True),
        ),
    ]
